### ISSUE TITLE
After code refactor, model backbone for r4.0 has changed

### ISSUE THREAD

**Issue by SarBH** [zhiqwang/yolov5-rt-stack#234] opened 2021-11-23 19:04 UTC
### 🐛 Describe the bug

Somewhere between these two commits there was a model backbone change: https://github.com/zhiqwang/yolov5-rt-stack/compare/06022fd...e3e18f2. The three MaxPool2d at `backbone.body.8.m.0, backbone.body.8.m.1, backbone.body.8.m.2` go from being parallel to being serialized in the later hash into just `backbone.body.8.m` with three outputs. (I'm using `nni==2.4` to prune the model, and a node with three outputs is a problem for that)

For example, the SMALL model. 
On the left: commit hash 06022fd, default upstream_version = r4.0
On the right: commit hash e3e18f2, default value for upstream_version changed with the addition of `r6.0`, so I set the `upstream_version=r4.0` explicitly.
![image](https://user-images.githubusercontent.com/30393837/143085174-b6f83604-8842-45e4-910a-eec1443838fc.png)
I see the same behavior for `'yolov5s', 'yolov5m', 'yolov5l'`

All else in the models remained the same, therefore I wondered if this was accidental. 

### Versions

```
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.14.4
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-4.14.252-195.483.amzn2.x86_64-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.2.142
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 450.142.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] mypy==0.910
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.5
[pip3] numpydoc==1.1.0
[pip3] pytorch-lightning==1.5.2
[pip3] pytorchcv==0.0.58
[pip3] segmentation-models-pytorch==0.2.1
[pip3] torch==1.7.1
[pip3] torchinfo==1.5.3
[pip3] torchmetrics==0.6.0
[pip3] torchvision==0.8.2
[conda] Could not collect
```

**Comment by zhiqwang** [comment] 2021-11-24 02:37
Hi @SarBH , Thanks for reporting this!

> All else in the models remained the same, therefore I wondered if this was accidental.

The origin of this change is in upstream YOLOv5 https://github.com/ultralytics/yolov5/pull/4420, the `SPPF` we used here is a faster version of `SPP`. I think it will also benefit the earlier version, as such we replace this part in <https://github.com/zhiqwang/yolov5-rt-stack/pull/194/commits/451f3e4be72700ab08c8a1617a5ef4cfc3d0869a> with a verification of numerical equality.

https://github.com/zhiqwang/yolov5-rt-stack/blob/4cba0437389e2cccbcc299ab196c922945c93d45/yolort/v5/models/common.py#L191-L208

> I'm using nni==2.4 to prune the model, and a node with three outputs is a problem for that

I don't really understand the intent here, could you provide me with more information, or a reproducible example? If the above change affects the use of downstream application, we can also revert the change back or we can work together to come up with a better way to handle this scenario.

**Comment by SarBH** [comment] 2021-11-30 17:12
Thanks for the follow up @zhiqwang, and for this awesome project!

I investigated where exactly pruning is failing:

the [compressor.py](https://github.com/microsoft/nni/blob/3601044e9435edf1081eac5509f3e928876b11ca/nni/compression/pytorch/speedup/compressor.py#L234) file asserts that `assert len(node.outputs) == 1, 'The number of the output should be one after the Tuple unpacked manually' `.  
I see that all other (non failing) nodes in this model indeed have a single output, but this one `MaxPool2d` node has 3 outputs after the update (Below is a printout of the node, see last line):
```
name: backbone.body.8.m, type: module, op_type: MaxPool2d, sub_nodes: 
['__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_aten::max_pool2d', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_aten::max_pool2d', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_aten::max_pool2d', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
'__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct'], 
inputs: ['input.85'], outputs: ['input.86', 'input.87', '4815'], aux: None 
```
The old hash’s model that doesnt fail prunning actually splits that `backbone.body.8.m` layer into `backbone.body.8.m.0, backbone.body.8.m.1, backbone.body.8.m.2` , but it is otherwise the same exact model.
![image](https://user-images.githubusercontent.com/30393837/144094686-24483595-378a-4be1-b953-413e2156a49b.png)

** Note: We are using an older version of nni package `nni==2.4` so I'm not sure if this is resolved already. 
I'm not an expert on pruning, but I hope this helps :)

**Comment by zhiqwang** [comment] 2021-12-01 03:52
> I see that all other (non failing) nodes in this model indeed have a single output, but this one MaxPool2d node has 3 outputs after the update.

Got it, Thanks for the details informations, it is very useful. I agree with you, we will revert this substitution it this two days.

**Comment by zhiqwang** [comment] 2021-12-01 05:03
Hi @SarBH , I revert the `SPPF` to `SPP` in #240 both in "r4.0" and "r6.0", and as such I'm closing this issue.

Please install the `yolort` from source (we'll distribute 0.6.0 at the end of the month.)

```bash
pip install -U 'git+https://github.com/zhiqwang/yolov5-rt-stack.git'
```

Thanks for your detailed information again, feel free to reopen this ticket or create another ticket if you have more questions.

**Closed** 2021-12-01 05:07 UTC
Labels: bug / fix

**Comment by syswyl** [comment] 2022-01-25 03:19
> Thanks for the follow up @zhiqwang, and for this awesome project!
> 
> I investigated where exactly pruning is failing:
> 
> the [compressor.py](https://github.com/microsoft/nni/blob/3601044e9435edf1081eac5509f3e928876b11ca/nni/compression/pytorch/speedup/compressor.py#L234) file asserts that `assert len(node.outputs) == 1, 'The number of the output should be one after the Tuple unpacked manually' `. I see that all other (non failing) nodes in this model indeed have a single output, but this one `MaxPool2d` node has 3 outputs after the update (Below is a printout of the node, see last line):
> 
> ```
> name: backbone.body.8.m, type: module, op_type: MaxPool2d, sub_nodes: 
> ['__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_aten::max_pool2d', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_aten::max_pool2d', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_aten::max_pool2d', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct', 
> '__module.backbone/__module.backbone.body/__module.backbone.body.8/__module.backbone.body.8.m_prim::ListConstruct'], 
> inputs: ['input.85'], outputs: ['input.86', 'input.87', '4815'], aux: None 
> ```
> 
> The old hash’s model that doesnt fail prunning actually splits that `backbone.body.8.m` layer into `backbone.body.8.m.0, backbone.body.8.m.1, backbone.body.8.m.2` , but it is otherwise the same exact model. ![image](https://user-images.githubusercontent.com/30393837/144094686-24483595-378a-4be1-b953-413e2156a49b.png)
> 
> ** Note: We are using an older version of nni package `nni==2.4` so I'm not sure if this is resolved already. From the fact that [compressor.py](https://github.com/microsoft/nni/blob/3601044e9435edf1081eac5509f3e928876b11ca/nni/compression/pytorch/speedup/compressor.py#L234) still has the assert im inclined to beleive new version will also fail. I'm not an expert on pruning, but I hope this helps :)

Hello  @SarBH , I encountered the same problem as you when using nni2.6. Considering the reason of sppf, I decided to use the [yolov5 version 5](https://github.com/ultralytics/yolov5/tree/v5.0), because the old version still uses the basic spp module, but the pruning process is still There is a new error, have you succeeded in pruning yolov5?
