### ISSUE TITLE
30 graphics card cannot use c++ for tensorrt reasoning

### ISSUE THREAD

**Issue by wangtianlong1994** [zhiqwang/yolov5-rt-stack#421] opened 2022-06-13 03:07 UTC
### 🐛 Describe the bug

Thank you for your project. I use tools export on the 20 series graphics card_ The engine model converted from the model can run normally on c++tensorrt, but the engine model converted on the 30 graphics card cannot run on c++tensorrt. I use the yolov5-m model structure. The size of the engine model converted on the 20 series graphics card is about 140MB, but the size of the 30 graphics card is only 86mb. I checked the onnx model and found that the two models are the same. The output of the tensorrt model conversion only changes in the size of the video memory and memory

The error message of tensorrt inference is:
     [executionContext.cpp::nvinfer1::rt::ExecutionContext::setBindingDimensions::926] Error Code 3: API Usage Error (Parameter check failed at: executionContext.cpp::nvinfer1::rt::ExecutionContext::setBindingDimensions::926, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles())
    [executionContext.cpp::nvinfer1::rt::ExecutionContext::enqueueInternal::318] Error Code 3: API Usage Error (Parameter check failed at: executionContext.cpp::nvinfer1::rt::ExecutionContext::enqueueInternal::318, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()

------------------------------------------------------------------------------------------
**30 graphics card PC model conversion output information:**
(yolo) E:\yolov5-rt-stack-main>python tools/export_model.py --checkpoint_path best_5_m.pt --include engine
Command Line Args: Namespace(batch_size=1, checkpoint_path='best_5_m.pt', image_size=[640, 640], include=['engine'], nms_thresh=0.45, onnx_path=None, opset=11, score_thresh=0.25, simplify=False, size_divisible=32, skip_preprocess=False, trt_path=None, version='r6.0')
Loaded saved model from best_5_m.pt
C:\Users\Administrator\.conda\envs\yolo\lib\site-packages\torch\functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
C:\Users\Administrator\.conda\envs\yolo\lib\site-packages\yolort\models\anchor_utils.py:46: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  anchors = torch.as_tensor(self.anchor_grids, dtype=torch.float32, device=device).to(dtype=dtype)
C:\Users\Administrator\.conda\envs\yolo\lib\site-packages\yolort\models\anchor_utils.py:47: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  strides = torch.as_tensor(self.strides, dtype=torch.float32, device=device).to(dtype=dtype)
C:\Users\Administrator\.conda\envs\yolo\lib\site-packages\yolort\relay\logits_decoder.py:45: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  strides = torch.as_tensor(self.strides, dtype=torch.float32, device=device).to(dtype=dtype)
C:\Users\Administrator\.conda\envs\yolo\lib\site-packages\yolort\models\box_head.py:337: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for head_output, grid, shift, stride in zip(head_outputs, grids, shifts, strides):
PyTorch2ONNX graph created successfully
[W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
[W] 'Shape tensor cast elision' routine failed with: None
Created NMS plugin 'EfficientNMS_TRT' with attributes: {'plugin_version': '1', 'background_class': -1, 'max_output_boxes': 100, 'score_threshold': 0.25, 'iou_threshold': 0.45, 'score_activation': False, 'box_coding': 0}
Saved ONNX model to best_5_m.trt.onnx
[06/13/2022-09:40:00] [TRT] [I] [MemUsageChange] Init CUDA: CPU +526, GPU +0, now: CPU 3868, GPU 1273 (MiB)
[06/13/2022-09:40:01] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 3927 MiB, GPU 1273 MiB
[06/13/2022-09:40:02] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 4137 MiB, GPU 1317 MiB
[06/13/2022-09:40:02] [TRT] [I] ----------------------------------------------------------------
[06/13/2022-09:40:02] [TRT] [I] Input filename:   best_5_m.trt.onnx
[06/13/2022-09:40:02] [TRT] [I] ONNX IR version:  0.0.8
[06/13/2022-09:40:02] [TRT] [I] Opset version:    11
[06/13/2022-09:40:02] [TRT] [I] Producer name:    pytorch
[06/13/2022-09:40:02] [TRT] [I] Producer version: 1.11.0
[06/13/2022-09:40:02] [TRT] [I] Domain:
[06/13/2022-09:40:02] [TRT] [I] Model version:    0
[06/13/2022-09:40:02] [TRT] [I] Doc string:
[06/13/2022-09:40:02] [TRT] [I] ----------------------------------------------------------------
[06/13/2022-09:40:02] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[06/13/2022-09:40:02] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[06/13/2022-09:40:02] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[06/13/2022-09:40:02] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[06/13/2022-09:40:02] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[06/13/2022-09:40:03] [TRT] [I] No importer registered for op: EfficientNMS_TRT. Attempting to import as plugin.
[06/13/2022-09:40:03] [TRT] [I] Searching for plugin: EfficientNMS_TRT, plugin_version: 1, plugin_namespace:
[06/13/2022-09:40:03] [TRT] [I] Successfully created plugin: EfficientNMS_TRT
Network Description
Input 'images' with shape (1, 3, 640, 640) and dtype DataType.FLOAT
Output 'num_detections' with shape (1, 1) and dtype DataType.INT32
Output 'detection_boxes' with shape (1, 100, 4) and dtype DataType.FLOAT
Output 'detection_scores' with shape (1, 100) and dtype DataType.FLOAT
Output 'detection_classes' with shape (1, 100) and dtype DataType.INT32
Building fp32 Engine in best_5_m.engine
Using fp32 mode.
[06/13/2022-09:40:11] [TRT] [W] TensorRT was linked against cuBLAS/cuBLASLt 11.6.3 but loaded cuBLAS/cuBLASLt 11.5.1
[06/13/2022-09:40:11] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +783, GPU +316, now: CPU 4994, GPU 1633 (MiB)
[06/13/2022-09:40:15] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +699, GPU +264, now: CPU 5693, GPU 1897 (MiB)
[06/13/2022-09:40:15] [TRT] [W] TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.2.0
[06/13/2022-09:40:15] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[06/13/2022-09:44:48] [TRT] [I] Detected 1 inputs and 4 output network tensors.
[06/13/2022-09:44:48] [TRT] [I] Total Host Persistent Memory: 157312
[06/13/2022-09:44:48] [TRT] [I] Total Device Persistent Memory: 13765632
[06/13/2022-09:44:48] [TRT] [I] Total Scratch Memory: 15879680
[06/13/2022-09:44:48] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 17 MiB, GPU 4914 MiB
[06/13/2022-09:44:48] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 49.1361ms to assign 7 blocks to 196 nodes requiring 53452800 bytes.
[06/13/2022-09:44:48] [TRT] [I] Total Activation Memory: 53452800
[06/13/2022-09:44:48] [TRT] [W] TensorRT was linked against cuBLAS/cuBLASLt 11.6.3 but loaded cuBLAS/cuBLASLt 11.5.1
[06/13/2022-09:44:48] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 6148, GPU 2393 (MiB)
[06/13/2022-09:44:48] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 6148, GPU 2401 (MiB)
[06/13/2022-09:44:48] [TRT] [W] TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.2.0
[06/13/2022-09:44:48] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +7, GPU +82, now: CPU 7, GPU 82 (MiB)
Serialize engine success, saved as best_5_m.engine

------------------------------------------------------------------------------------------------
**20 graphics card PC model conversion output information:**
(tensorRT) D:\yolov5-rt-stack-main>python tools/export_model.py --checkpoint_path best_5_m.pt --include engine 
Command Line Args: Namespace(batch_size=1, checkpoint_path='best_5_m.pt', image_size=[640, 640], include=['engine'], nms_thresh=0.45, onnx_path=None, opset=11, score_thresh=0.25, simplif
y=False, size_divisible=32, skip_preprocess=False, trt_path=None, version='r6.0')
Loaded saved model from best_5_m.pt
C:\Users\QC\Anaconda3\envs\tensorRT\lib\site-packages\torch\functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Tr
iggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
C:\Users\QC\Anaconda3\envs\tensorRT\lib\site-packages\yolort\models\anchor_utils.py:46: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ig
nore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the t
race to be incorrect.
  anchors = torch.as_tensor(self.anchor_grids, dtype=torch.float32, device=device).to(dtype=dtype)
C:\Users\QC\Anaconda3\envs\tensorRT\lib\site-packages\yolort\models\anchor_utils.py:47: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ig
nore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the t
race to be incorrect.
  strides = torch.as_tensor(self.strides, dtype=torch.float32, device=device).to(dtype=dtype)
C:\Users\QC\Anaconda3\envs\tensorRT\lib\site-packages\yolort\relay\logits_decoder.py:45: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely i
gnore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the 
trace to be incorrect.
  strides = torch.as_tensor(self.strides, dtype=torch.float32, device=device).to(dtype=dtype)
C:\Users\QC\Anaconda3\envs\tensorRT\lib\site-packages\yolort\models\box_head.py:337: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of dif
ferent shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for head_output, grid, shift, stride in zip(head_outputs, grids, shifts, strides):
PyTorch2ONNX graph created successfully
[W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
[W] 'Shape tensor cast elision' routine failed with: None
Created NMS plugin 'EfficientNMS_TRT' with attributes: {'plugin_version': '1', 'background_class': -1, 'max_output_boxes': 100, 'score_threshold': 0.25, 'iou_threshold': 0.45, 'score_act
ivation': False, 'box_coding': 0}
Saved ONNX model to best_5_m.trt.onnx
[06/13/2022-08:46:53] [TRT] [I] [MemUsageChange] Init CUDA: CPU +415, GPU +0, now: CPU 6132, GPU 1154 (MiB)
[06/13/2022-08:46:53] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 6194 MiB, GPU 1154 MiB
[06/13/2022-08:46:53] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 6332 MiB, GPU 1190 MiB
[06/13/2022-08:46:53] [TRT] [I] ----------------------------------------------------------------
[06/13/2022-08:46:53] [TRT] [I] Input filename:   best_5_m.trt.onnx
[06/13/2022-08:46:53] [TRT] [I] ONNX IR version:  0.0.8
[06/13/2022-08:46:53] [TRT] [I] Opset version:    11
[06/13/2022-08:46:53] [TRT] [I] Producer name:    
[06/13/2022-08:46:53] [TRT] [I] Producer version:
[06/13/2022-08:46:53] [TRT] [I] Domain:
[06/13/2022-08:46:53] [TRT] [I] Model version:    0
[06/13/2022-08:46:53] [TRT] [I] Doc string:
[06/13/2022-08:46:53] [TRT] [I] ----------------------------------------------------------------
[06/13/2022-08:46:53] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to 
INT32.
[06/13/2022-08:46:53] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[06/13/2022-08:46:53] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[06/13/2022-08:46:53] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[06/13/2022-08:46:53] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[06/13/2022-08:46:53] [TRT] [I] No importer registered for op: EfficientNMS_TRT. Attempting to import as plugin.
[06/13/2022-08:46:53] [TRT] [I] Searching for plugin: EfficientNMS_TRT, plugin_version: 1, plugin_namespace:
[06/13/2022-08:46:53] [TRT] [I] Successfully created plugin: EfficientNMS_TRT
Network Description
Input 'images' with shape (1, 3, 640, 640) and dtype DataType.FLOAT
Output 'num_detections' with shape (1, 1) and dtype DataType.INT32
Output 'detection_boxes' with shape (1, 100, 4) and dtype DataType.FLOAT
Output 'detection_scores' with shape (1, 100) and dtype DataType.FLOAT
Output 'detection_classes' with shape (1, 100) and dtype DataType.INT32
Building fp32 Engine in best_5_m.engine
Using fp32 mode.
[06/13/2022-08:46:54] [TRT] [W] TensorRT was linked against cuBLAS/cuBLASLt 11.6.3 but loaded cuBLAS/cuBLASLt 11.5.1
[06/13/2022-08:46:54] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +518, GPU +206, now: CPU 6889, GPU 1396 (MiB)
[06/13/2022-08:46:54] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +433, GPU +170, now: CPU 7322, GPU 1566 (MiB)
[06/13/2022-08:46:54] [TRT] [W] TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.2.0
[06/13/2022-08:46:54] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[06/13/2022-08:50:09] [TRT] [I] Detected 1 inputs and 4 output network tensors.
[06/13/2022-08:50:09] [TRT] [I] Total Host Persistent Memory: 166464
[06/13/2022-08:50:09] [TRT] [I] Total Device Persistent Memory: 149347840
[06/13/2022-08:50:09] [TRT] [I] Total Scratch Memory: 2419712
[06/13/2022-08:50:09] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 17 MiB, GPU 4914 MiB
[06/13/2022-08:50:09] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 34.4966ms to assign 7 blocks to 155 nodes requiring 53452800 bytes.
[06/13/2022-08:50:09] [TRT] [I] Total Activation Memory: 53452800
[06/13/2022-08:50:09] [TRT] [W] TensorRT was linked against cuBLAS/cuBLASLt 11.6.3 but loaded cuBLAS/cuBLASLt 11.5.1
[06/13/2022-08:50:09] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 8175, GPU 1886 (MiB)
[06/13/2022-08:50:09] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 8175, GPU 1894 (MiB)
[06/13/2022-08:50:09] [TRT] [W] TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.2.0
[06/13/2022-08:50:09] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +7, GPU +145, now: CPU 7, GPU 145 (MiB)
Serialize engine success, saved as best_5_m.engine

### Versions

30 graphics card computer environment:
Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 教育版
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19042-SP0
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070
Nvidia driver version: 471.11
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h59b6b97_2
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py38h2bbff1b_0
[conda] mkl_fft                   1.3.1            py38h277e83a_0
[conda] mkl_random                1.2.2            py38hf11a4ad_0
[conda] numpy                     1.22.3           py38h7a0a035_0
[conda] numpy-base                1.22.3           py38hca35cd5_0
[conda] pytorch                   1.11.0          py3.8_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.11.0               py38_cu113    pytorch
[conda] torchvision               0.12.0               py38_cu113    pytorch

**Comment by zhiqwang** [comment] 2022-06-13 03:29
Hi @wangtianlong1994 , Thanks for the detail info here, I guess the problem is due to the TensorRT version, could you double check the version of TensorRT on your two 20 and 30 series graphics?

**Comment by wangtianlong1994** [comment] 2022-06-13 04:04
@zhiqwang Thank you for your reply. I checked that the 20 GPU CUDA version is 11.4, cudnn version is 8.2.4, tensorrt version is 8.2.4, 30 GPU  CUDA version is 11.1, cudnn version is 8.0.4, tensorrt version is 8.2.4, and the tensorrt installation packages of 20 and 30 use the same package。

**Comment by zhiqwang** [comment] 2022-06-13 05:42
Hi @wangtianlong1994 , Could you try to replace the `cudaMemcpy` to `CudaMemcpyAsync` in the following:

https://github.com/zhiqwang/yolov5-rt-stack/blob/a7441069dde4ea958d5059e069d0ad2c308e45be/deployment/tensorrt/main.cpp#L382-L408

**Comment by zhiqwang** [comment] 2022-06-13 06:25
BTW, Seems the cudnn version is a bit outdated, would you mind upgrading to 8.2.1+? Check https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel-8-2-4 for more details.

**Comment by zhiqwang** [comment] 2022-06-13 07:50
I guess that there is a new cudnn on the conda environment. For example, a more suitable version of cudnn may be automatically selected when installing PyTorch.

**Comment by zhiqwang** [comment] 2022-06-13 09:05
> When I enter Conda, cuBLAS/cuBLASLt version is 11.5.1

That's the power of conda! 😄

Because the origin problem of this issue is solved, I'll close this thread, and feel free to reopen of create a new ticket if you have more questions.

**Closed by zhiqwang** 2022-06-13 09:05 UTC
Labels: question, dependencies
